/**
 * Spring Boot REST API
 * \"Spring Boot REST API for Pivotal Developer Training\"
 *
 * OpenAPI spec version: 1.0.0
 * Contact: miguel@thingtrack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductId } from './productId';


/**
 * Class representing a product.
 */
export interface Product {
    id?: ProductId;
    /**
     * Description of the product.
     */
    description?: string;
    /**
     * Price of the product.
     */
    price: number;
    /**
     * Status of the product.
     */
    active: boolean;
}
