/**
 * Spring Boot REST API
 * \"Spring Boot REST API for Pivotal Developer Training\"
 *
 * OpenAPI spec version: 1.0.0
 * Contact: miguel@thingtrack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductId {
    productKey?: number;
    productVersion?: number;
}
